DROP TABLE IF EXISTs alunos;

CREATE TABLE alunos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTEAMP,
    NOME TEXT NOT NULL,
    matricula TEXT NOT NULL
);